version: '3.8'
services:
  # modeling tool
  plantuml:
    image: plantuml/plantuml-server
    container_name: "plantuml"
    ports:
      - ${UML}:8080
    restart: always
  # api tool
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - ${EDITOR}:8080
