openapi: 3.0.0
info:
  title: Ice Cream Shop API
  description: Order System API.
  contact:
    name: API support
    url: http://www.onesword618.com/support
    email: support@onesword618.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://dev.sample-server.com/v1
    description: Development server
paths:
  /orders:
    get:
      tags:
        - orders
      summary: Get Orders.
      description: Returns an Order model
      parameters: []
      responses:
        '200':
          description: A JSON array of Order model
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jane Doe
